flask/flaskday4/早晨内容/FlaskDay4/FlashApp/__init__.py
import redis
from flask import Flask
from flask_session import Session

from FlashApp.views import blue


def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "abcdef"
    app.config["SESSION_TYPE"] = "redis"
    app.config["SESSION_REDIS"] = redis.Redis(host="localhost",port=6379,db=3)
    app.config["SESSION_KEY_PREFIX"] = "python1905"
    app.register_blueprint(blue)
    Session(app)
    return app

flask/flaskday4/早晨内容/FlaskDay4/FlashApp/views.py
from flask import Blueprint, request, render_template, session, redirect, url_for, flash

blue = Blueprint("myblue",__name__)


@blue.route("/login/",methods=["GET","POST"])
def login_view():
    if request.method == "GET":
        return render_template("login.html")   # 加载登录模板
    elif request.method == "POST":
        logname = request.form.get("logname")  # 获取请求体中的参数
        logpwd = request.form.get("logpwd")  # 获取请求体中的参数
        if logname == "tom" and logpwd == "123456":
            session["username"] = logname  # 如果登录验证成功，则添加一个session属性
            return redirect(url_for("myblue.welcome_view"))   # 重定向到欢迎页面
        else:   # 如果验证失败
            flash("用户名或密码错误，请重新输入！")   # flash将信息存储于session中
            flash("认真点！")
            return redirect(url_for("myblue.login_view"))   # 重定向到登录页面


@blue.route("/wel/")
def welcome_view():
    return render_template("welcome.html")


@blue.route("/logout/")
def logout_view():
    session.clear()  # 删除session信息
    return redirect(url_for("myblue.login_view"))  # 重定向到登录页面

flask/flaskday4/早晨内容/FlaskDay4/FlashApp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
</head>
<body>
    <ol>
    {% for msg in get_flashed_messages() %}
         <h4 style="color:red"> <li> {{ msg }} </li> </h4>
    {% endfor %}
    </ol>
    
    <form action="{{ url_for('myblue.login_view') }}" method="post">
        登录名：<input type="text" name="logname"/>  <br/>
        登录密码：<input type="password" name="logpwd"/> <br/>
        <input type="submit" value="登录"/>
    </form>
</body>
</html>

flask/flaskday4/早晨内容/FlaskDay4/FlashApp/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎页面</title>
</head>
<body>
    {% if session["username"] %}
        <h3 style="color:blue">欢迎你，<span style="color:green"> {{ session["username"] }} </span></h3>
        <a href="{{ url_for('myblue.logout_view') }}">登出</a>
    {% else %}
        <h3>您还未登录，请先<a href="{{ url_for('myblue.login_view') }}">登录</a></h3>
    {% endif %}

</body>
</html>